### PR TITLE
Add author field

### PR DESCRIPTION
**Pull request by szabgab**
See also: https://pydigger.com/docs/author

### CODE REVIEW

**Comment by unnown** [comment]
Please mark as invalid and spam, this is an obvious attempt to get a free t-shirt by 'contributing'(hacktoberfest)
This will also ban the user for trying to abuse the system by doing marginal effort

**Comment by szabgab** [comment]
Wow, someone decided to spam GitHub. Several of my PRs got this comment (but none of the PRs that my projects received). Disregard it. Use your own judgement. I've reported this abuse to GitHub.

**Comment by unnown** [comment]
You reported yourself? good idea, OR..., simply apply the tag invalid (which bans him from hacktoberfest) and accept the pr
If he truelly wishes to help and this pr isn't a cheap excuse... he wouldn't mind right?

**Comment by smarie** [comment]
See https://github.com/smarie/python-pyfields/pull/80 : same conclusion to stay away from this debate. But thanks for pointing out !

**Pull request closed without merging**
